# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181212_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='carts',
            new_name='cart',
        ),
    ]
