# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(blank=True, default='default.svg.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
