# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180829_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='pCategory',
            field=models.ManyToManyField(related_name='cTproduct_id', to='product.Product'),
        ),
        migrations.RemoveField(
            model_name='color',
            name='pColor',
        ),
        migrations.AddField(
            model_name='color',
            name='pColor',
            field=models.ManyToManyField(related_name='cProduct_id', to='product.Product'),
        ),
        migrations.RemoveField(
            model_name='size',
            name='pSize',
        ),
        migrations.AddField(
            model_name='size',
            name='pSize',
            field=models.ManyToManyField(related_name='sProduct_id', to='product.Product'),
        ),
    ]
