# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180909_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cName',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='cName',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='sName',
        ),
    ]
