# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180914_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='cName',
            new_name='coName',
        ),
    ]
