# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180829_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='pCategory',
            field=models.ManyToManyField(related_name='cCategory_id', to='product.Category'),
        ),
    ]
